version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
    open-pull-requests-limit: 10
    reviewers:
      - "@dependabot"