# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in vizzly.gemspec
gemspec

group :development, :test do
  gem 'minitest', '~> 5.0'
  gem 'rake', '~> 13.0'
  gem 'rubocop', '~> 1.60'
  gem 'selenium-webdriver', '~> 4.0'
end
